import { IFoodItem, FoodCategory } from "@/types/foodTypes";

export const dataTest: IFoodItem[] = [
  {
    id: "1",
    name: "Pomme",
    category: FoodCategory.Fruits,
    isDry: false,
    quantity: 1,
    unit: "pcs",
    expirationDate: new Date(),
  },
  {
    id: "2",
    name: "Poire",
    category: FoodCategory.Fruits,
    isDry: false,
    quantity: 2,
    unit: "pcs",
    expirationDate: new Date(),
  },
  {
    id: "3",
    name: "Pâtes",
    category: FoodCategory.Cereals,
    isDry: true,
    quantity: 1,
    unit: "kg",
    expirationDate: new Date(),
  },
  {
    id: "4",
    name: "Raw Beef",
    category: FoodCategory.Proteins,
    isDry: false,
    quantity: 500,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "5",
    name: "Cheese",
    category: FoodCategory.Dairy,
    isDry: false,
    quantity: 350,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "6",
    name: "Cheese",
    category: FoodCategory.Dairy,
    isDry: false,
    quantity: 350,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "7",
    name: "Cheese",
    category: FoodCategory.Dairy,
    isDry: false,
    quantity: 350,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "8",
    name: "Cheese",
    category: FoodCategory.Dairy,
    isDry: false,
    quantity: 350,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "9",
    name: "Cheese",
    category: FoodCategory.Dairy,
    isDry: false,
    quantity: 350,
    unit: "g",
    expirationDate: new Date(),
  },
  {
    id: "12",
    name: "Pomme",
    category: FoodCategory.Fruits,
    isDry: false,
    quantity: 1,
    unit: "pcs",
    expirationDate: new Date(),
  },
  {
    id: "21",
    name: "Poire",
    category: FoodCategory.Fruits,
    isDry: false,
    quantity: 2,
    unit: "pcs",
    expirationDate: new Date(),
  },
  {
    id: "32",
    name: "Pâtes",
    category: FoodCategory.Cereals,
    isDry: true,
    quantity: 1,
    unit: "kg",
    expirationDate: new Date(),
  },
  {
    id: "43",
    name: "Raw Beef",
    category: FoodCategory.Proteins,
    isDry: false,
    quantity: 500,
    unit: "g",
    expirationDate: new Date(),
  },
];
